### ISSUE TITLE
Peer conected, bad argument L2255

### ISSUE THREAD

**Issue by tami5** [jbyuki/instant.nvim#2] opened 2020-12-03 09:34 UTC
Hey @jbyuki awesome project. I'm looking to experiment with and learn from it so thanks.

I've setup heroku server then executed `InstantJoinSession damp-tundra-81540.herokuapp.com`  

I get the following error:

```vim
Error executing vim.schedule lua callback: 
...e/nvim/site/pack/packer/opt/instant.nvim/lua/instant.lua:2255: 
bad argument #1 to 'insert' (table expected, got nil)
```

**Comment by tami5** [comment] 2020-12-03 09:37
`table.insert(events, "ERROR: Tried to join an empty server")` Somehow there is no events table and thats what causing part of the issue

**Comment by jbyuki** [comment] 2020-12-03 10:08
Hey, thanks for the kind words. Hope your experimentation will bring you something.

Thanks for the bug feedback as well. This shouldn't be too difficult to resolve.

This is caused by some debug code that I left (all table.insert(events,... ), they could be probably removed but I will do a quick commit to fix that.

Also I see you use ```InstantJoinSession [host]``` to connect, is it the first client?

If not you should use ```InstantStartSession [host]``` and the error should be gone.

I will do a quick fix.

**Comment by jbyuki** [comment] 2020-12-03 10:14
e10a6791547bf15cf0c7ad54a4c535260af0a3e1 should do it. Thanks again.

**Comment by tami5** [comment] 2020-12-03 10:34
Oh nice thanks @jbyuki , So First I start session then let my friend join right. We are getting the following error
`Error executing vim.schedule lua callback: .../conni/.config/nvim/plugged/instant.nvim/lua/instant.lua:1583: bad argument #1 to 'insert' (table expected, got nil)`

**Comment by tami5** [comment] 2020-12-03 10:35
``Error executing vim.schedule lua callback: ...e/nvim/site/pack/packer/opt/instant.nvim/lua/instant.lua:719: Vim:E474: Trailing characters: [7,117,"conni"]``

**Comment by jbyuki** [comment] 2020-12-03 10:42
Yes, first start the session and then connect. Maybe it should be more clear in the README.
Ok, I see, I will get back to you in a moment.

**Comment by tami5** [comment] 2020-12-03 10:50
Error executing vim.schedule lua callback: ...e/nvim/site/pack/packer/opt/instant.nvim/lua/instant.lua:976: bad argument #1 to 'ipairs' (table expected, got nil)

|| Error executing vim.schedule lua callback: .../conni/.config/nvim/plugged/instant.nvim/lua/instant.lua:1236: bad argument #1 to 'insert' (table expected, got nil)

|| Error executing vim.schedule lua callback: .../conni/.config/nvim/plugged/instant.nvim/lua/instant.lua:719: Vim:E474: Trailing characters: [6, "", [123, 2], [0, 699274, 1048576], []]

|| Error executing vim.schedule lua callback: .../conni/.config/nvim/plugged/instant.nvim/lua/instant.lua:719: Vim:E474: Trailing characters: [6, "", [123, 2], [0, 699274, 1048576], []][6, "", [123, 9], [0, 425234, 1048576], []]

Error executing vim.schedule lua callback: ...e/nvim/site/pack/packer/opt/instant.nvim/lua/instant.lua:721: Vim:E474: Trailing characters: [8,124]


So far instantJoinSingle worked for us the other is err resulting from session

**Comment by tami5** [comment] 2020-12-03 10:53
Error executing lua callback: ...e/nvim/site/pack/packer/opt/instant.nvim/lua/instant.lua:2069: attempt to index upvalue 'prev' (a nil value)

When trying  InstantFollow

|| Connected!
|| Error executing vim.schedule lua callback: .../conni/.config/nvim/plugged/instant.nvim/lua/instant.lua:1879: bad argument #1 to 'insert' (table expected, got nil)
|| Error executing vim.schedule lua callback: .../conni/.config/nvim/plugged/instant.nvim/lua/instant.lua:1879: bad argument #1 to 'insert' (table expected, got nil)
|| Connected. 0 other client(s)
|| Connected. 0 other client(s)
|| Error executing vim.schedule lua callback: .../conni/.config/nvim/plugged/instant.nvim/lua/instant.lua:719: Vim:E474: Trailing characters: [7,126,"tami5"]
|| Error executing vim.schedule lua callback: .../conni/.config/nvim/plugged/instant.nvim/lua/instant.lua:719: Vim:E474: Trailing characters: [7,126,"tami5"][3]

**Comment by tami5** [comment] 2020-12-03 11:12
After some time of expermenting on Single 
![](https://i.imgur.com/Ro4eLbL.png)

**Comment by jbyuki** [comment] 2020-12-03 11:17
The trailing character issue seems to be linked to network fragmentation.
I should have fixed that in a previous commit.

Did you guys update instant.nvim to the latest commit?
The error line numbers don't seem to match to the current files as well. 

```
Error executing vim.schedule lua callback: .../conni/.config/nvim/plugged/instant.nvim/lua/instant.lua:1583: bad argument #1 to 'insert' (table expected, got nil)
```

The current file doesn't contain this line at https://github.com/jbyuki/instant.nvim/blob/e10a6791547bf15cf0c7ad54a4c535260af0a3e1/lua/instant.lua#L1583

If that was it, try updating both clients.
If not, I will continue investigating the issue.

**Comment by jbyuki** [comment] 2020-12-03 11:39
Also make sure, the server files are up to date.

**Comment by tami5** [comment] 2020-12-03 11:47
@jbyuki me and @conni2461 had an amazing time testing and experimenting with instant.nvim. So far InstantJoin/Start Single worked well for us, as well as InstantFollow. Although some point in our instant the connection broke.

We will do further testing some time this week and report back here.
Also, I'll remember to update server files along with the plugin.

Thanks a lot, again amazing work :smile:

**Comment by jbyuki** [comment] 2020-12-03 12:04
Great, glad I could provide you both with some fun experimenting.

The plugin is still rather unstable so really any help will be very helpful.

Thanks again, and see you soon then.

**Comment by jbyuki** [comment] 2020-12-06 20:26
Closing this for now as the initial bug was fixed.

**Closed by jbyuki** 2020-12-06 20:26 UTC
Labels: bug
